version: '3'
services:
  housepricing:
    build: .
    image: pengedy/housepricing
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./log:/app/HousePricing/log
      - ./tmp:/app/HousePricing/tmp
    env_file:
      - ./app.env
    ports:
      - "3000:3000"
